### ISSUE TITLE
Thank you! you save my project!

### ISSUE THREAD

**Issue by Personuo** [hobosore/UnityVMDPlayer#1]
Running a humanoid skeleton with vmd at runtime was always the technology I wanted. You make it！

**Comment by Personuo** [comment]
Make some suggestions and identify problems:

1. Rotation causes IK problem, which can be easily fixed by setting the rotation position before running, but with a lot of local and world coordinates mixed, I can't handle the problem of rotating IK at runtime.

2.list.find causes a lot of gc, you can write your own dichotomous algorithm and frame buffer repair (can done to 0 GC).

3. DefaultBoneAmplifier can be dynamically adjusted, with an approximate algorithm of character leg length/10.5.

**Comment by hobosore** [comment]
Thank you, Personuo.
I am sorry that I did not notice your suggestions.

1. This seems to be a difficult problem. In MMD, any runtime operation is not expected.
   A new algorithm may be necessary to solve it.

2. Your suggestion is totally right. I should have avoided List.find, and it should be rewritten.
   Could you let me know whether or not "foreach and if" strategy can solve this problem?

3. Is it true? Could you let me know why it works?

I am afraid to say that I am too busy these days, so it may be difficult to fix many parts.

**Comment by Personuo** [comment]
2.In my final solution, I use "for and if" to solve this problem.But, if you use "for" to retrieve from 0, a dance is generally 3 minutes, and when the time is after 2 minutes, the calculation is also very large,

3.I think how DefaultBoneAmplifier and leg length to maintain the same ratio, Ik will not lead to strange movements of the character, such as ik too far from the leg caused by leg stiffness，but this is not the perfect solution, it can not solve the leg penetration problem (The knees are not position in the same proportion)
